### ISSUE TITLE
Does Valentine currently support SemProp and EmbDI?

### ISSUE THREAD

**Issue by Molimicha-tech** [delftdata/valentine#41]
I saw "we implement and integrate six schema matching algorithms [14]–[19] and our own baseline method, and adapt them to the needs of dataset discovery" in your paper. At present, Valentine does not seem to support these two algorithms.

**Comment by kPsarakis** [comment]
The original experimental suite version of Valentine, as first published for the needs of the research paper, can be still found [here](https://github.com/delftdata/valentine/tree/v1.1).

Where both EMBDI and SemProp are integrated. We didn't integrate them to the python package due to their long runtime and heavy dependency requirements.
